### ISSUE TITLE
Get a sample of song lyrics transliterations

### ISSUE THREAD

**Issue by anasm-17** [anasm-17/lyrics_transliteration#2]

**Comment by anasm-17** [comment]
@nikihajmoshir could you modify "scraping.ipynb" file from pull request #1 to put the output in a tabular format (pandas data frame).

  | Pinyin text| Chinese Text|
0| ~~~~~~~|~~~~~~~~|
1| ~~~~~~~|~~~~~~~~|

And so on.

**Comment by nikihajmoshir** [comment]
It's done and ready for the next step!
